#server:
#  port: 8130
#
#spring:
#  profiles:
#    active: dev
#  application:
#    name: service-oss
#  servlet:
#    multipart:
#      max-file-size: 500MB
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#
#aliyun:
#  oss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    key-id: LTAI4G9tvhemhxKBCtT92mLW
#    key-secret: cP0WjLLPFcRMAgmT9L2o5341Nbp0GD
#    bucketname: inf-files
